var axios = require('axios');
var express = require('express');
var app = express();
var url ;
var port = process.env.PORT || 8989;
var logger = require('logger').createLogger('development.log'); // logs to a file
logger.format = function(level, date, message) {
  return date.getTime().toString() + "; " + message;
};
app.use(express.static('build'));


app.get('/', (req,res) => {
	re.send('index.html');
});


app.get('/tracker', (req,res) => {
	res.header("Access-Control-Allow-Origin", "*");
	res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
	axios.get('https://tms.adititracking.com/tracking_data.php?action=json&user_name=sahil@gmail.com&hash_key=HEPDCJAUTJ')
		.then(function (response) {
			// console.log(response.data.data.vehicles);
			// res.send(response.data.data.vehicles);
		})
		.catch(function (error) {
			console.log(error);
		});
	res.send([ { device_id: '9662',
    device_serial: '9967899900',
    voice_no: null,
    sim_no: null,
    serial_no: '9967899900',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '9967899900',
    start_date: '2018-02-06 13:16:38.02586',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'SAHIL',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-09 11:46:34',
    latitude: '19.250973',
    longitude: '72.862616',
    altitude: '0',
    direction: '0',
    ignition_status: '0',
    comp_stamp: '2018-02-06 13:16:38.02586',
    geofence_id: null,
    speed: '0',
    reporting_interval_stopped: '600',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: 'T= 55 , SC = 10 , RC = 45',
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '85',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-06 13:16:38.02586',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-06 13:16:38.02586',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-06 13:16:38.02586',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: '645',
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-06 13:16:38.02586',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: '2018-02-09 11:46:13',
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-06 13:16:38',
    installment_period_to: '2018-02-06 13:16:38',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null },
  { device_id: '9669',
    device_serial: '9619547771',
    voice_no: null,
    sim_no: null,
    serial_no: '9619547771',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '9619547771',
    start_date: '2018-02-07 11:00:40.009085',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'ALI',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-09 18:28:22',
    latitude: '19.048044',
    longitude: '72.824578',
    altitude: '0',
    direction: '0',
    ignition_status: '0',
    comp_stamp: '2018-02-07 11:00:40.009085',
    geofence_id: null,
    speed: '0',
    reporting_interval_stopped: '600',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: 'Testing',
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '40',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-07 11:00:40.009085',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-07 11:00:40.009085',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-07 11:00:40.009085',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: '320',
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-07 11:00:40.009085',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: '2018-02-09 18:28:22',
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-07 11:00:40',
    installment_period_to: '2018-02-07 11:00:40',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null },
  { device_id: '9670',
    device_serial: '9892121809',
    voice_no: null,
    sim_no: null,
    serial_no: '9892121809',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '9892121809',
    start_date: '2018-02-07 11:10:43.247227',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'Akbar',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-07 19:18:27',
    latitude: '18.986709',
    longitude: '72.824968',
    altitude: '0',
    direction: '0',
    ignition_status: '1',
    comp_stamp: '2018-02-07 11:10:43.247227',
    geofence_id: null,
    speed: '5',
    reporting_interval_stopped: '60',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: null,
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '47',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-07 11:10:43.247227',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-07 11:10:43.247227',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-07 11:10:43.247227',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: '40',
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-07 11:10:43.247227',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: '2018-02-07 19:18:27',
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-07 11:10:43.247227',
    installment_period_to: '2018-02-07 11:10:43.247227',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null },
  { device_id: '9671',
    device_serial: '7021868611',
    voice_no: null,
    sim_no: null,
    serial_no: '7021868611',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '7021868611',
    start_date: '2018-02-07 11:42:46.427248',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'Noor',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-07 11:45:23',
    latitude: '18.969500',
    longitude: '72.836638',
    altitude: '0',
    direction: '0',
    ignition_status: '0',
    comp_stamp: '2018-02-07 11:42:46.427248',
    geofence_id: null,
    speed: '0',
    reporting_interval_stopped: '60',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: null,
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '49',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-07 11:42:46.427248',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-07 11:42:46.427248',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-07 11:42:46.427248',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: '1',
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-07 11:42:46.427248',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: '2018-02-07 11:43:39',
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-07 11:42:46.427248',
    installment_period_to: '2018-02-07 11:42:46.427248',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null },
  { device_id: '9674',
    device_serial: '9820282109',
    voice_no: null,
    sim_no: null,
    serial_no: '9820282109',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '9820282109',
    start_date: '2018-02-07 12:30:20.759521',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'Shamshuji',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-09 16:40:48',
    latitude: '19.051378',
    longitude: '72.823668',
    altitude: '0',
    direction: '0',
    ignition_status: '0',
    comp_stamp: '2018-02-07 12:30:20.759521',
    geofence_id: null,
    speed: '0',
    reporting_interval_stopped: '60',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: null,
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '44',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-07 12:30:20.759521',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-07 12:30:20.759521',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-07 12:30:20.759521',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: '388',
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-07 12:30:20.759521',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: '2018-02-09 16:40:48',
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-07 12:30:20.759521',
    installment_period_to: '2018-02-07 12:30:20.759521',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null },
  { device_id: '9675',
    device_serial: '9820474644',
    voice_no: null,
    sim_no: null,
    serial_no: '9820474644',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '9820474644',
    start_date: '2018-02-07 15:31:16.958284',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'Aziz sir',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-09 19:33:05',
    latitude: '19.050178',
    longitude: '72.825785',
    altitude: '0',
    direction: '0',
    ignition_status: '0',
    comp_stamp: '2018-02-07 15:31:16.958284',
    geofence_id: null,
    speed: '0',
    reporting_interval_stopped: '60',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: null,
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '43',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-07 15:31:16.958284',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-07 15:31:16.958284',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-07 15:31:16.958284',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: '420',
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-07 15:31:16.958284',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: '2018-02-09 19:30:21',
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-07 15:31:16.958284',
    installment_period_to: '2018-02-07 15:31:16.958284',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null },
  { device_id: '9676',
    device_serial: '9833882669',
    voice_no: null,
    sim_no: null,
    serial_no: '9833882669',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '9833882669',
    start_date: '2018-02-07 16:00:34.979405',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'Sahir Mira',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-09 09:07:48',
    latitude: '19.279768',
    longitude: '72.870263',
    altitude: '0',
    direction: '0',
    ignition_status: '0',
    comp_stamp: '2018-02-07 16:00:34.979405',
    geofence_id: null,
    speed: '0',
    reporting_interval_stopped: '60',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: null,
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '58',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-07 16:00:34.979405',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-07 16:00:34.979405',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-07 16:00:34.979405',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: '2',
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-07 16:00:34.979405',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: '2018-02-09 09:05:08',
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-07 16:00:34.979405',
    installment_period_to: '2018-02-07 16:00:34.979405',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null },
  { device_id: '9677',
    device_serial: '9768268201',
    voice_no: null,
    sim_no: null,
    serial_no: '9768268201',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '9768268201',
    start_date: '2018-02-07 16:01:42.179613',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'rukruudin',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-07 16:01:42.179613',
    latitude: '000000000',
    longitude: '000000000',
    altitude: '0',
    direction: '0',
    ignition_status: '0',
    comp_stamp: '2018-02-07 16:01:42.179613',
    geofence_id: null,
    speed: '0',
    reporting_interval_stopped: '60',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: null,
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '0',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-07 16:01:42.179613',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-07 16:01:42.179613',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-07 16:01:42.179613',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: null,
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-07 16:01:42.179613',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: null,
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-07 16:01:42.179613',
    installment_period_to: '2018-02-07 16:01:42.179613',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null },
  { device_id: '9678',
    device_serial: '9820226629',
    voice_no: null,
    sim_no: null,
    serial_no: '9820226629',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '9820226629',
    start_date: '2018-02-07 16:13:16.487445',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'salim sir',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-09 19:18:41',
    latitude: '22.994157',
    longitude: '72.532308',
    altitude: '0',
    direction: '0',
    ignition_status: '1',
    comp_stamp: '2018-02-07 16:13:16.487445',
    geofence_id: null,
    speed: '1.46',
    reporting_interval_stopped: '60',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: null,
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '18',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-07 16:13:16.487445',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-07 16:13:16.487445',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-07 16:13:16.487445',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: '701',
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-07 16:13:16.487445',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: '2018-02-09 19:10:56',
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-07 16:13:16.487445',
    installment_period_to: '2018-02-07 16:13:16.487445',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null },
  { device_id: '9679',
    device_serial: '9769688622',
    voice_no: null,
    sim_no: null,
    serial_no: '9769688622',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '9769688622',
    start_date: '2018-02-07 16:54:14.05867',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'suleman sir',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-09 20:06:59',
    latitude: '19.048751',
    longitude: '72.826253',
    altitude: '0',
    direction: '0',
    ignition_status: '0',
    comp_stamp: '2018-02-07 16:54:14.05867',
    geofence_id: null,
    speed: '0',
    reporting_interval_stopped: '60',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: null,
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '9',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-07 16:54:14.05867',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-07 16:54:14.05867',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-07 16:54:14.05867',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: '486',
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-07 16:54:14.05867',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: '2018-02-09 19:17:21',
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-07 16:54:14.05867',
    installment_period_to: '2018-02-07 16:54:14.05867',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null },
  { device_id: '9680',
    device_serial: '9987877700',
    voice_no: null,
    sim_no: null,
    serial_no: '9987877700',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '9987877700',
    start_date: '2018-02-07 17:08:34.330199',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'asif sir',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-07 22:18:54',
    latitude: '19.250025',
    longitude: '72.863889',
    altitude: '0',
    direction: '0',
    ignition_status: '1',
    comp_stamp: '2018-02-07 17:08:34.330199',
    geofence_id: null,
    speed: '5',
    reporting_interval_stopped: '60',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: null,
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '2',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-07 17:08:34.330199',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-07 17:08:34.330199',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-07 17:08:34.330199',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: '198',
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-07 17:08:34.330199',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: '2018-02-07 22:17:58',
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-07 17:08:34.330199',
    installment_period_to: '2018-02-07 17:08:34.330199',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null },
  { device_id: '9681',
    device_serial: '9821894464',
    voice_no: null,
    sim_no: null,
    serial_no: '9821894464',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '9821894464',
    start_date: '2018-02-07 17:34:18.577081',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'parvez sir',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-09 20:06:37',
    latitude: '19.151276',
    longitude: '72.832880',
    altitude: '0',
    direction: '0',
    ignition_status: '1',
    comp_stamp: '2018-02-07 17:34:18.577081',
    geofence_id: null,
    speed: '5',
    reporting_interval_stopped: '60',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: null,
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '61',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-07 17:34:18.577081',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-07 17:34:18.577081',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-07 17:34:18.577081',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: '1174',
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-07 17:34:18.577081',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: '2018-02-09 20:06:26',
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-07 17:34:18.577081',
    installment_period_to: '2018-02-07 17:34:18.577081',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null },
  { device_id: '9682',
    device_serial: '9769168976',
    voice_no: null,
    sim_no: null,
    serial_no: '9769168976',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '9769168976',
    start_date: '2018-02-07 18:08:22.584462',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'sameer',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-07 18:08:22.584462',
    latitude: '000000000',
    longitude: '000000000',
    altitude: '0',
    direction: '0',
    ignition_status: '0',
    comp_stamp: '2018-02-07 18:08:22.584462',
    geofence_id: null,
    speed: '0',
    reporting_interval_stopped: '60',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: null,
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '0',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-07 18:08:22.584462',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-07 18:08:22.584462',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-07 18:08:22.584462',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: null,
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-07 18:08:22.584462',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: null,
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-07 18:08:22.584462',
    installment_period_to: '2018-02-07 18:08:22.584462',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null },
  { device_id: '9683',
    device_serial: '9819551046',
    voice_no: null,
    sim_no: null,
    serial_no: '9819551046',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '9819551046',
    start_date: '2018-02-08 04:59:30.556453',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'azim',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-09 18:38:50',
    latitude: '19.280773',
    longitude: '72.870594',
    altitude: '0',
    direction: '0',
    ignition_status: '0',
    comp_stamp: '2018-02-08 04:59:30.556453',
    geofence_id: null,
    speed: '0',
    reporting_interval_stopped: '60',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: null,
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '20',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-08 04:59:30.556453',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-08 04:59:30.556453',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-08 04:59:30.556453',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: '591',
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-08 04:59:30.556453',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: '2018-02-09 18:38:50',
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-08 04:59:30.556453',
    installment_period_to: '2018-02-08 04:59:30.556453',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null },
  { device_id: '9684',
    device_serial: '9619775877',
    voice_no: null,
    sim_no: null,
    serial_no: '9619775877',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '9619775877',
    start_date: '2018-02-08 05:40:23.904979',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'farooq sir',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-08 18:43:27',
    latitude: '19.137093',
    longitude: '72.811645',
    altitude: '0',
    direction: '0',
    ignition_status: '1',
    comp_stamp: '2018-02-08 05:40:23.904979',
    geofence_id: null,
    speed: '1.24',
    reporting_interval_stopped: '60',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: null,
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '18',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-08 05:40:23.904979',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-08 05:40:23.904979',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-08 05:40:23.904979',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: '531',
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-08 05:40:23.904979',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: '2018-02-08 18:27:34',
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-08 05:40:23.904979',
    installment_period_to: '2018-02-08 05:40:23.904979',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null },
  { device_id: '9686',
    device_serial: '9819848486',
    voice_no: null,
    sim_no: null,
    serial_no: '9819848486',
    reporting_interval: '10',
    scheme_id: '0',
    mobile_no: '9819848486',
    start_date: '2018-02-09 18:31:17.140418',
    fence_id: '0',
    status: '0',
    log_report_for: '90',
    registration_no: 'Bandra 1',
    device_icon_set: null,
    vehicle_type_id: '1',
    device_type_id: '63',
    driver_name: 'A',
    speed_limit: null,
    device_code: null,
    last_update: '2018-02-09 18:31:17.140418',
    latitude: '000000000',
    longitude: '000000000',
    altitude: '0',
    direction: '0',
    ignition_status: '0',
    comp_stamp: '2018-02-09 18:31:17.140418',
    geofence_id: null,
    speed: '0',
    reporting_interval_stopped: '60',
    log_file_duration: '15',
    device_reporting_ip: '0.0.0.0',
    device_reporting_port: null,
    device_tag: null,
    digital_sensor_status: '0',
    gps_odometer: '0',
    record_status: '0',
    analog_data: null,
    analog_data_layout: null,
    digital_sensor_layout: null,
    gmt_correction: '0',
    fuel_level: '0',
    engine_no: null,
    chassis_no: null,
    purchase_date: null,
    fuel_level_change_threshold: null,
    fuel_level_position: '-1',
    seating_capacity: null,
    timeout_interval: '1800',
    vehicle_model: null,
    vehicle_make: null,
    owner_phone: null,
    owner_name: null,
    auth_key_validity: null,
    auth_key: null,
    vehicle_photo: null,
    unit_rate: '450',
    fuel_level_percentage: null,
    dispatch_status: '0',
    relay_status: '0',
    relay_status_layout: null,
    alert_status_time: '2018-02-09 18:31:17.140418',
    alert_type_id: null,
    dispatch_lock_time: '2018-02-09 18:31:17.140418',
    dispatch_location_id: null,
    dispatch_location_update_source: '0',
    dispatch_location_time: '2018-02-09 18:31:17.140418',
    vehicle_status: null,
    device_pin: '0000',
    device_note: null,
    po_number: null,
    billing_term: '1',
    next_billing_date: null,
    billing_status: '0',
    app_type: '0',
    app_id: null,
    humidity: '0',
    temperature: '0',
    camera_status: '0',
    driver_image: null,
    driver_rating: '0',
    gps_data_id: null,
    no_of_rating: '0',
    fuel_tank_capacity: null,
    save_raw_log: null,
    fuel_mileage: '10',
    socket_id: null,
    process_id: null,
    server_name: null,
    gmt_difference_for_consolidated_data: null,
    installation_date: '2018-02-09 18:31:17.140418',
    tax_name: null,
    tax_value: null,
    currency: null,
    tax_type: null,
    billing_package: null,
    record_start_date: null,
    fleetvendor_id: null,
    manual_odometer: null,
    driver_id: null,
    vehicle_fuel_type: null,
    vehicle_segment: null,
    loan_from: null,
    installment_amount: null,
    installment_period: null,
    vehicle_lease_to: null,
    vehicle_model_id: null,
    installment_period_from: '2018-02-09 18:31:17.140418',
    installment_period_to: '2018-02-09 18:31:17.140418',
    analog_voltage: null,
    standard_average: null,
    registration_date: null,
    vehicle_make_id: null,
    vehiclesegment_id: null,
    vehicle_color: null,
    insurance_from: null,
    dispatch_mode: null,
    vehiclebrand_id: '0',
    alert_type_name: null,
    alert_icon: null } ])

	// axios.get('https://tms.adititracking.com/tracking_data.php?action=json&user_name=sahil@gmail.com&hash_key=HEPDCJAUTJ')
	// .then((data) => {
	// 	console.log(data);
	// 	res.send(data);
	// })
	// .catch((err) => {
	// 	console.log(err);
	// 	res.send(err)
	// });
	
});


// app.get('/:loc', (req, res) => {
// 	res.header("Access-Control-Allow-Origin", "*");
// 	res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
	
// 	var com;
// 	if (req.params.loc.indexOf(',') > 1) {
// 		var location = req.params.loc;

// 		url = `https://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins=${req.params.loc}&destinations=Mazgaon, Anjeerwadi Road, Rambhau Bhogle Marg, Mustafa Bazar, Mazgaon, Mumbai, Maharashtra 400010&key=AIzaSyBfVvEY-tpaxhLBcQqslPDQrr5hWrvp2P4`;

// 		url = url.indexOf(" ") > 0 ? url.replace(" ", "") : url;
// 		console.log(url)
// 		axios.get(url)
// 			.then(
// 			(data) => {
// 				com = data.data.rows[0].elements;
// 				console.log(com);
// 				com = com.map(elem => elem['duration'].text);
// 				res.send(com[0]);
// 			})
// 			.catch((err) => {
// 				console.log(err);
// 				res.send(err)
// 			});
// 	}
// 	else {
// 		res.send('pur proper location');
// 	}
// });

app.listen(port, (req, res, port) => {
	// console.log(port);
});